#!/bin/bash
if [[ ! -f /etc/modprobe.d/blacklist-rtc_ds1307.conf ]]
then
    echo "blacklist rtc_ds1307" > /etc/modprobe.d/blacklist-rtc_ds1307.conf 
fi


if [[ -z "$(grep rtc-rx8130 /etc/modules)"  ]];
then 
    echo "Adding rtc-rx8130 to /etc/modules ..."
    echo 'rtc-rx8130' >> /etc/modules
    depmod
fi

echo "Please add 'dtoverlay=mrhat-rx8130' if needed, then reboot ..."


