#!/bin/bash
echo "Removing module autoload for rtc-rx8130 ..."
sed -ri '/^\s*rtc-rx8130/d' /etc/modules

echo "Removing rtc_ds1307 blacklist ..."
rm -f /etc/modprobe.d/blacklist-rtc_ds1307.conf

depmod

echo "Removal of mrhat-rx8130 completed, please remove 'dtoverlay=mrhat-rx8130' from /boot/config.txt if not needed anymore then reboot ..."
